services:
  # === MongoDB ===
  mongodb:
    image: mongo:6
    container_name: ms_mongodb
    restart: always
    ports:
      - '27018:27017' # đổi port để tránh trùng
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - ms_mongo_data:/data/db

  # === Mongo Express ===
  mongo-express:
    image: mongo-express
    container_name: ms_mongo_express
    restart: always
    ports:
      - '8082:8081' # đổi port để tránh trùng
    environment:
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      ME_CONFIG_BASICAUTH_USERNAME: ${MONGO_EXPRESS_ROOT_ACCOUNT}
      ME_CONFIG_BASICAUTH_PASSWORD: ${MONGO_EXPRESS_ROOT_ACCOUNT}
    depends_on:
      - mongodb

  # === MailHog (SMTP testing) ===
  mailhog:
    image: mailhog/mailhog
    container_name: ms_mailhog
    restart: always
    ports:
      - '1026:1025'
      - '8026:8025'

  # === MinIO (File storage) ===
  minio:
    image: minio/minio
    container_name: ms_minio
    restart: always
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    command: server /data --console-address ":9001"
    ports:
      - '9002:9000' # đổi port để tránh trùng
      - '9003:9001'
    volumes:
      - ms_minio_data:/data

  # === Zookeeper (Kafka dependency) ===
  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: ms_zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: ms_kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE: 'true'
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
    depends_on:
      - zookeeper


volumes:
  ms_mongo_data:
    name: ms_mongo_data
  ms_minio_data:
    name: ms_minio_data
